export const lorenIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis massa a ante eleifend, at malesuada odio lobortis. Vivamus lobortis, nunc ut egestas rhoncus, est tortor dignissim est, nec congue nunc velit sed arcu. Sed sed accumsan risus. Etiam faucibus accumsan fermentum. In mattis interdum velit, ac tincidunt libero. Nunc suscipit dui nunc, vitae tempor orci euismod nec. Curabitur tristique quis lorem eu lobortis. Morbi odio lorem, porta id pretium commodo, vestibulum eu lacus. Mauris luctus sagittis augue, ac finibus orci auctor in. Pellentesque arcu tortor, vestibulum placerat sollicitudin vitae, accumsan nec magna. Cras molestie nisl tellus, vitae iaculis mi elementum vitae. Sed at malesuada dolor.

Aenean eget justo egestas, faucibus turpis eu, euismod est. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec blandit erat lacus, nec suscipit eros bibendum nec. Nullam vitae neque turpis. Praesent vel efficitur neque. Sed dignissim urna porttitor nisi cursus eleifend.

Vivamus ut ultricies sapien. Cras fringilla placerat maximus. Maecenas eget varius nulla, sed varius purus. Maecenas vestibulum, eros non faucibus eleifend, odio lacus vehicula lectus, vitae vestibulum dui tellus sollicitudin ex. Integer dapibus, justo at mollis porttitor, leo risus dapibus magna, vitae bibendum mi magna sed leo. Nam fringilla dolor ac massa pulvinar placerat. Nullam sit amet eleifend lectus. Maecenas eleifend nibh quis cursus convallis. Nam ut vehicula ante, vitae eleifend urna.

Nam pellentesque nulla vel risus cursus rutrum. Mauris blandit et orci non ultrices. Integer feugiat ex id neque faucibus, at fermentum dolor gravida. Proin metus nunc, eleifend nec pulvinar sit amet, faucibus vel metus. Sed rutrum ut erat id lacinia. Ut egestas sapien at ipsum gravida, dignissim aliquet nibh iaculis. Proin libero felis, condimentum ut eleifend non, euismod et odio. Curabitur auctor odio nec nisl vehicula, finibus dapibus nisi sodales. Phasellus cursus eget ligula a ultricies. Fusce eget erat risus.

Cras vitae aliquet est. Aliquam lorem libero, dignissim ut elit eget, aliquam ultrices magna. Quisque hendrerit leo ut sodales finibus. Praesent vestibulum risus at viverra euismod. Pellentesque lobortis turpis dictum mi condimentum, sed fringilla nisi sagittis. Fusce quis sodales libero. Phasellus nec hendrerit dolor. Aliquam sagittis euismod lorem, eget tincidunt mauris rutrum non. In luctus vitae tellus sed faucibus. Quisque in gravida massa, accumsan fermentum massa. Aliquam faucibus quis erat eget maximus. Vivamus molestie nulla nec facilisis tempor.`;
